//
//  LYNotifyCenter.h
//  Yingying
//
//  Created by 林伟池 on 15/12/4.
//  Copyright © 2015年 林伟池. All rights reserved.
//

#ifndef LYNotifyCenter_h
#define LYNotifyCenter_h


//UI
#define NOTIFY_UI_DISTRIBUTION_MOOD             @"NOTIFY_UI_DISTRIBUTION_MOOD"

#define NOTIFY_UI_DISTRIBUTION_RES              @"NOTIFY_UI_DISTRIBUTION_RES"

#define NOTIFY_UI_OPEN_AROUND_DETAIL_BOARD      @"NOTIFY_UI_OPEN_AROUND_DETAIL_BOARD"


#define NOTIFY_UI_MODAL_PERSONAL_HOME_PAGE      @"NOTIFY_UI_MODAL_PERSONAL_HOME_PAGE"

#define NOTIFY_UI_DELETE_PHOTO                  @"NOTIFY_UI_DELETE_PHOTO"

#define NOTIFY_UI_PERSONAL_HOMEPAGE_ADD_PHOTO   @"NOTIFY_UI_PERSONAL_HOMEPAGE_ADD_PHOTO"

#define NOTIFY_UI_REQUEST_TO_CHAT               @"NOTIFY_UI_REQUEST_TO_CHAT"

//CHAT
#define NOTIFY_CHAT_LOGIN_WITH_UID_SUCCESS      @"NOTIFY_CHAT_LOGIN_WITH_UID_SUCCESS"


//SERVER
#define NOTIFY_SERVER_LOGIN_SUCCESS             @"NOTIFY_SERVER_LOGIN_SUCCESS"
#define NOTIFY_SERVER_REGISTER_SUCCESS          @"NOTIFY_SERVER_REGISTER_SUCCESS"
#define NOTIFY_SERVER_EDIT_USERINFO_SUCCESS     @"NOTIFY_SERVER_EDIT_USERINFO_SUCCESS"
#define NOTIFY_SERVER_GET_USERINFO_SUCCESS      @"NOTIFY_SERVER_GET_USERINFO_SUCCESS"

//PROGRESS
#define NOTIFY_PROGRESS_UPLOAD                  @"NOTIFY_SERVER_PROGRESS_UPLOAD"

//MODEL
#define NOTIFY_MODEL_USER_MODEL_CHANGE          @"NOTIFY_MODEL_USER_MODEL_CHANGE"


#endif /* LYNotifyCenter_h */
